spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api01
          uri: lb://api01-server # 注册中心中名为 resource-server 的服务
          predicates:
            - Path=/api01/** # 匹配路径，以 resource 开头的请求会转发到 resource-server 服务上
          filters:
            - StripPrefix=1 # 去掉路径前缀
        - id: api02
          uri: lb://api02-server # 注册中心中名为 api-server 的服务
          predicates:
            - Path=/api02/** # 匹配路径，以 api 开头的请求会转发到 api-server 服务上
          filters:
            - StripPrefix=1 # 去掉路径前缀

server:
  port: 7811


# knife4j 网关聚合
knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 业务服务01
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /api01/api01/v2/api-docs?group=default
        service-name: api01
        context-path: /api01
        order: 1
      - name: 业务服务02
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /api02/api02/v2/api-docs?group=default
        service-name: api02
        context-path: /api02
        order: 2
