spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api01
          uri: lb://api01-server # 注册中心中名为 resource-server 的服务
          predicates:
            - Path=/api01/** # 匹配路径，以 resource 开头的请求会转发到 resource-server 服务上
          filters:
            - StripPrefix=1 # 去掉路径前缀
        - id: api02
          uri: lb://api02-server # 注册中心中名为 api-server 的服务
          predicates:
            - Path=/api02/** # 匹配路径，以 api 开头的请求会转发到 api-server 服务上
          filters:
            - StripPrefix=1 # 去掉路径前缀

server:
  port: 7811
